version: "3.8"
services:
  api-gateway:
    build: .
    image: api-gateway
    container_name: bank-api-gateway
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ACCOUNTS_URL: ${ACCOUNTS_URL}
      TRANSACTIONS_URL: ${TRANSACTIONS_URL}
      PAYMENTS_URL: ${PAYMENTS_URL}
      CARDS_URL: ${CARDS_URL}
      AUTH_URL: ${AUTH_URL}
    ports:
      - "4000:4000"
